[irc.libera]
Server="irc.libera.chat:6697"
Nick="DCGLUG[Bridge]"
NickServNick="DCGLUG[Bridge]"
UseTLS=true
UseSASL=false
SkipTLSVerify=true
Label="irc"
RemoteNickFormat="[{LABEL}] <{NOPINGNICK}> "
EditDisable=true
MessageSplit=true

[matrix.matrix]
Server="https://matrix.org"
Login="dcglug-bridge-bot"
Label="matrix"
RemoteNickFormat="[{LABEL}] <{NOPINGNICK}> "
NoHomeServerSuffix=false
PrefixMessagesWithNick=true
ReplaceNicks = [["Peri", "dwd"]]

[[gateway]]
name="dcglug"
enable=true

[[gateway.inout]]
account="irc.libera"
channel="#DCGLUG"

[[gateway.inout]]
account="matrix.matrix"
channel="!STzYxbWvWcLbCrgqgn:matrix.org"
